
name: 'React Pipeline'

on:
 push:
  branches:
  - master
 workflow_dispatch:

permissions:
    id-token: write
    contents: read




jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: check out code
              run: actions/checkout@v4
            
            - name: Login to Azure
              uses: azure/login@v1
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
            
            - name: Deploy WebApp
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v2
              with:
                app-name: "WebApp-with-BA-gitrepo"
                slot-name: "Production"
                package: .
            


            
        
            


